name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: apt update && apt install openssl-dev -y
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
